### ISSUE TITLE
cannot build with gc-8.0

### ISSUE THREAD

**Issue by juhp** [TieDyedDevil/XS#14]
I having trouble building xs for Fedora 32 which is still in development (downstream [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1800280)).

```
$ rpm -q gcc-c++ boost gc
gcc-c++-10.0.1-0.8.fc32.x86_64
boost-1.69.0-14.fc32.x86_64
gc-8.0.4-3.fc32.x86_64
```

I haven't updated the Fedora package in quite a while.
The above bug report is based on a snapshot from commit 22afec1 and fails in Fedora 32 (gc-8.0) like this:

```
[43/78] c++  -o xsdump 'xsdump@exe/meson-generated_.._parse.cxx.o' 'xsdump@exe/meson-generated_.._sigmsgs.cxx.o' 'xsdump@exe/dump.cxx.o' 'xsdump@exe/access.cxx.o' 'xsdump@exe/closure.cxx.o' 'xsdump@exe/conv.cxx.o' 'xsdump@exe/eval.cxx.o' 'xsdump@exe/fd.cxx.o' 'xsdump@exe/glob.cxx.o' 'xsdump@exe/glom.cxx.o' 'xsdump@exe/heredoc.cxx.o' 'xsdump@exe/input.cxx.o' 'xsdump@exe/list.cxx.o' 'xsdump@exe/main.cxx.o' 'xsdump@exe/match.cxx.o' 'xsdump@exe/opt.cxx.o' 'xsdump@exe/prim-ctl.cxx.o' 'xsdump@exe/prim.cxx.o' 'xsdump@exe/prim-etc.cxx.o' 'xsdump@exe/prim-io.cxx.o' 'xsdump@exe/prim-rel.cxx.o' 'xsdump@exe/prim-sys.cxx.o' 'xsdump@exe/print.cxx.o' 'xsdump@exe/proc.cxx.o' 'xsdump@exe/signal.cxx.o' 'xsdump@exe/split.cxx.o' 'xsdump@exe/status.cxx.o' 'xsdump@exe/str.cxx.o' 'xsdump@exe/syntax.cxx.o' 'xsdump@exe/term.cxx.o' 'xsdump@exe/token.cxx.o' 'xsdump@exe/tree.cxx.o' 'xsdump@exe/util.cxx.o' 'xsdump@exe/var.cxx.o' 'xsdump@exe/version.cxx.o' -Wl,--as-needed -Wl,--no-undefined -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=zEC12 -mtune=z13 -fasynchronous-unwind-tables -fstack-clash-protection -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--start-group -lreadline -lgc -lffi -Wl,--end-group
FAILED: xsdump 
c++  -o xsdump 'xsdump@exe/meson-generated_.._parse.cxx.o' 'xsdump@exe/meson-generated_.._sigmsgs.cxx.o' 'xsdump@exe/dump.cxx.o' 'xsdump@exe/access.cxx.o' 'xsdump@exe/closure.cxx.o' 'xsdump@exe/conv.cxx.o' 'xsdump@exe/eval.cxx.o' 'xsdump@exe/fd.cxx.o' 'xsdump@exe/glob.cxx.o' 'xsdump@exe/glom.cxx.o' 'xsdump@exe/heredoc.cxx.o' 'xsdump@exe/input.cxx.o' 'xsdump@exe/list.cxx.o' 'xsdump@exe/main.cxx.o' 'xsdump@exe/match.cxx.o' 'xsdump@exe/opt.cxx.o' 'xsdump@exe/prim-ctl.cxx.o' 'xsdump@exe/prim.cxx.o' 'xsdump@exe/prim-etc.cxx.o' 'xsdump@exe/prim-io.cxx.o' 'xsdump@exe/prim-rel.cxx.o' 'xsdump@exe/prim-sys.cxx.o' 'xsdump@exe/print.cxx.o' 'xsdump@exe/proc.cxx.o' 'xsdump@exe/signal.cxx.o' 'xsdump@exe/split.cxx.o' 'xsdump@exe/status.cxx.o' 'xsdump@exe/str.cxx.o' 'xsdump@exe/syntax.cxx.o' 'xsdump@exe/term.cxx.o' 'xsdump@exe/token.cxx.o' 'xsdump@exe/tree.cxx.o' 'xsdump@exe/util.cxx.o' 'xsdump@exe/var.cxx.o' 'xsdump@exe/version.cxx.o' -Wl,--as-needed -Wl,--no-undefined -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=zEC12 -mtune=z13 -fasynchronous-unwind-tables -fstack-clash-protection -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--start-group -lreadline -lgc -lffi -Wl,--end-group
/usr/bin/ld: xsdump@exe/closure.cxx.o: in function `operator new(unsigned long, GCPlacement, void (*)(void*, void*), void*)':
/usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: /usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: /usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: /usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: xsdump@exe/list.cxx.o: in function `operator new(unsigned long, GCPlacement, void (*)(void*, void*), void*)':
/usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: xsdump@exe/list.cxx.o:/usr/include/gc/gc_cpp.h:545: more undefined references to `GC_throw_bad_alloc()' follow
collect2: error: ld returned 1 exit status
```
(It builds fine on Fedora 31 (gc-7.6).)

The same thing basically happens with current upstream git HEAD, it also builds fine on Fedora 31, but again in Fedora 32:

```
FAILED: xsdump 
c++  -o xsdump 'xsdump@exe/meson-generated_.._parse.cxx.o' 'xsdump@exe/meson-generated_.._sigmsgs.cxx.o' 'xsdump@exe/src_dump.cxx.o' 'xsdump@exe/src_access.cxx.o' 'xsdump@exe/src_closure.cxx.o' 'xsdump@exe/src_conv.cxx.o' 'xsdump@exe/src_eval.cxx.o' 'xsdump@exe/src_fd.cxx.o' 'xsdump@exe/src_glob.cxx.o' 'xsdump@exe/src_glom.cxx.o' 'xsdump@exe/src_heredoc.cxx.o' 'xsdump@exe/src_input.cxx.o' 'xsdump@exe/src_list.cxx.o' 'xsdump@exe/src_main.cxx.o' 'xsdump@exe/src_match.cxx.o' 'xsdump@exe/src_opt.cxx.o' 'xsdump@exe/src_prim-ctl.cxx.o' 'xsdump@exe/src_prim.cxx.o' 'xsdump@exe/src_prim-etc.cxx.o' 'xsdump@exe/src_prim-io.cxx.o' 'xsdump@exe/src_prim-rel.cxx.o' 'xsdump@exe/src_prim-sys.cxx.o' 'xsdump@exe/src_print.cxx.o' 'xsdump@exe/src_proc.cxx.o' 'xsdump@exe/src_signal.cxx.o' 'xsdump@exe/src_split.cxx.o' 'xsdump@exe/src_status.cxx.o' 'xsdump@exe/src_str.cxx.o' 'xsdump@exe/src_syntax.cxx.o' 'xsdump@exe/src_term.cxx.o' 'xsdump@exe/src_token.cxx.o' 'xsdump@exe/src_tree.cxx.o' 'xsdump@exe/src_util.cxx.o' 'xsdump@exe/src_var.cxx.o' 'xsdump@exe/src_version.cxx.o' -Wl,--as-needed -Wl,--no-undefined -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--start-group /usr/lib64/libreadline.so -lgc -lffi -Wl,--end-group
/usr/bin/ld: xsdump@exe/src_closure.cxx.o: in function `operator new(unsigned long, GCPlacement, void (*)(void*, void*), void*)':
/usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: /usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: /usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: xsdump@exe/src_list.cxx.o: in function `operator new(unsigned long, GCPlacement, void (*)(void*, void*), void*)':
/usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: /usr/include/gc/gc_cpp.h:545: undefined reference to `GC_throw_bad_alloc()'
/usr/bin/ld: xsdump@exe/src_list.cxx.o:/usr/include/gc/gc_cpp.h:545: more undefined references to `GC_throw_bad_alloc()' follow
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
I confirmed that downgrading gc to 7.6 in the Fedora 32 build fixes the build, though there are 3 test failures:

```
/xs/XS-22afec159ebc9124cbaa31601e823ab454c33b6e/./tests
{match 'TEST: hello world'} failed
Failed:  Simple alias operates
{match 'TEST2: bye-bye world'} failed
Failed:  Self-referring alias does not recurse
{match 'ALIASED: TESTNOALIAS'} failed
Failed:  Temporary alias disappears
```

**Comment by TieDyedDevil** [comment]
Looks like this is relevant: https://github.com/ivmai/bdwgc/issues/268

**Comment by TieDyedDevil** [comment]
Resolved by also linking libgccpp.

9592d9b192a79653e86ae934170b6743ceac2164

**Comment by juhp** [comment]
Thank you, I have built latest xs for Fedora 31+.
